# Generated by Django 6.0.4 on 2026-04-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_product_delete_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(default='Genérica', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='preço',
            field=models.FloatField(default=0),
        ),
    ]
