# Generated by Django 6.0.4 on 2026-04-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_product_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
