# Generated by Django 6.0.4 on 2026-04-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_product_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='imagem',
            field=models.ImageField(upload_to='produtos/'),
        ),
    ]
